### ISSUE TITLE
Out of memory when deploying TabbyML/CodeLlama-7B in Modal with default Modal app.py script

### ISSUE THREAD

**Issue by costanzo** [TabbyML/tabby#749]
**Describe the bug**
Out of memory when deploying TabbyML/CodeLlama-7B in Modal with default Modal app.py script

**Information about your version**
```
IMAGE_NAME = "tabbyml/tabby:0.5.4"
MODEL_ID = "TabbyML/CodeLlama-7B"
GPU_CONFIG = gpu.T4()
```

**Information about your GPU**
T4

**Additional context**

Complete Modal script:

```py
"""Usage:
modal serve app.py
"""

from modal import Image, Stub, asgi_app, gpu

IMAGE_NAME = "tabbyml/tabby:0.5.4"
MODEL_ID = "TabbyML/CodeLlama-7B"
GPU_CONFIG = gpu.T4()


def download_model():
    import subprocess

    subprocess.run(
        [
            "/opt/tabby/bin/tabby",
            "download",
            "--model",
            MODEL_ID,
        ]
    )


image = (
    Image.from_registry(
        IMAGE_NAME,
        add_python="3.11",
    )
    .dockerfile_commands("ENTRYPOINT []")
    .run_function(download_model)
    .pip_install("asgi-proxy-lib")
)

stub = Stub("tabby-server-" + MODEL_ID.split("/")[-1], image=image)


@stub.function(
    gpu=GPU_CONFIG,
    allow_concurrent_inputs=10,
    container_idle_timeout=120,
    timeout=360,
)
@asgi_app()
def app():
    import socket
    import subprocess
    import time
    from asgi_proxy import asgi_proxy

    launcher = subprocess.Popen(
        [
            "/opt/tabby/bin/tabby",
            "serve",
            "--model",
            MODEL_ID,
            "--port",
            "8000",
            "--device",
            "cuda",
        ]
    )

    # Poll until webserver at 127.0.0.1:8000 accepts connections before running inputs.
    def tabby_ready():
        try:
            socket.create_connection(("127.0.0.1", 8000), timeout=1).close()
            return True
        except (socket.timeout, ConnectionRefusedError):
            # Check if launcher webserving process has exited.
            # If so, a connection can never be made.
            retcode = launcher.poll()
            if retcode is not None:
                raise RuntimeError(f"launcher exited unexpectedly with code {retcode}")
            return False

    while not tabby_ready():
        time.sleep(1.0)

    print("Tabby server ready!")
    return asgi_proxy("http://localhost:8000")
```

Error message:

```shell
RuntimeError: launcher exited unexpectedly with code 1
Runner failed with exception: RuntimeError('launcher exited unexpectedly with code 1')
2023-11-10T14:35:27+0000 User exception caught, exiting
Request failed with exception: RuntimeError('launcher exited unexpectedly with code 1') (execution time: 1699626927860.1 ms, first-byte latency: 13498.9 ms)
[2m2023-11-10T14:35:29.812901Z[0m [32m INFO[0m [2mtabby::serve[0m[2m:[0m [2mcrates/tabby/src/serve/mod.rs[0m[2m:[0m[2m146:[0m Starting server, this might takes a few minutes...
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: Tesla T4, compute capability 7.5

CUDA error 2 at /root/workspace/crates/llama-cpp-bindings/llama.cpp/ggml-cuda.cu:7641: out of memory
current device: 0
Traceback (most recent call last):
  File "/root/tabby-setup.py", line 67, in tabby_ready
    socket.create_connection(("127.0.0.1", 8000), timeout=1).close()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 335, in handle_user_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 718, in main
    imp_fun = import_function(container_args.function_def, ser_cls, ser_fun, container_args.serialized_params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/modal/_container_entrypoint.py", line 671, in import_function
    asgi_app = fun()
               ^^^^^
  File "/root/tabby-setup.py", line 77, in app
    while not tabby_ready():
              ^^^^^^^^^^^^^
  File "/root/tabby-setup.py", line 74, in tabby_ready
    raise RuntimeError(f"launcher exited unexpectedly with code {retcode}")
RuntimeError: launcher exited unexpectedly with code 1
Runner failed with exception: RuntimeError('launcher exited unexpectedly with code 1')
2023-11-10T14:35:40+0000 User exception caught, exiting
[2m2023-11-10T14:35:46.481729Z[0m [32m INFO[0m [2mtabby::serve[0m[2m:[0m [2mcrates/tabby/src/serve/mod.rs[0m[2m:[0m[2m146:[0m Starting server, this might takes a few minutes...
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: Tesla T4, compute capability 7.5
| Running (0/1 containers active)... View app at https://modal.com/apps/ap-YIyY2zDZ5WUJUMRtCBEFm8
```
![20231110223644](https://github.com/TabbyML/tabby/assets/15900473/45235f89-3093-4d43-9cdb-3163101c15fc)

**Comment by erfanium** [comment]
@costanzo 
Try with the latest version. or use `--parallelism 1` flag

**Comment by wsxiaoys** [comment]
Please refer https://github.com/TabbyML/tabby/issues/726 for the discussion

**Comment by costanzo** [comment]
Thanks. I added the environment variable `LLAMA_CPP_PARALLELISM=1` in script and it's now working.

```python
from modal import Image, Stub, asgi_app, gpu
import os

IMAGE_NAME = "tabbyml/tabby:0.5.5"
MODEL_ID = "TabbyML/CodeLlama-7B"
GPU_CONFIG = gpu.T4()
os.environ["LLAMA_CPP_PARALLELISM"] = "1"
...
```
